computing upper-bound...
# preprocessing : initial upper-bound         = 38334.00
computing lower-bound...
# preprocessing : initial lower-bound         = 36714.00
applying reduction...
# preprocessing : removed edges               = 32382
# preprocessing : ratio removed edges         = 19.69
iter = 0
# hello callback!
# SECs added: 3
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 7
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 3
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 3
# hello callback!
# SECs added: 5
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 5
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 4
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 3
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 3
# hello callback!
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
# hello callback!
# SECs added: 2
SOLSTAT = 101
feas. sol = 38321.000000
# discarded fat edges = 33058
opt                 = 38321.00
time                = 323.62
